import React from "react";
import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 py-16 px-4 sm:px-8 font-sans">
      <div className="max-w-3xl mx-auto bg-white p-8 sm:p-12 rounded-3xl border border-slate-200/80 shadow-sm">
        <div className="mb-8 flex items-center justify-between">
          <Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Go Back Home
          </Link>
          <FileText className="w-8 h-8 text-amber-500" />
        </div>
        <h1 className="text-3xl font-black mb-6 text-slate-950 font-display">Terms of Service</h1>
        <div className="text-sm text-slate-600 space-y-4 leading-relaxed">
          <p className="font-bold">Last Updated: June 12, 2026</p>
          <p>By accessing or navigating the Raimond Solar Pvt Ltd platform, you agree to comply with and be bound by the following Terms of Service:</p>
          <p><strong>1. Private Enterprise Disclaimer:</strong> Raimond Solar Pvt Ltd is an independent, private solar engineering organization and MNRE list-integrated solar installation vendor in West Bengal. We are not a government entity, nor are we representing PM Surya Ghar Scheme directly. Any government portal submissions are cooperative assistance services.</p>
          <p><strong>2. Quote & Estimates Accuracy:</strong> Calculations, ROI estimations, and subsidy numbers generated by the on-site calculator tool are highly detailed estimations intended purely for engineering and budgetary analysis. Actual price sheets vary depending on spatial layout constraints, roof shading, sub-district wiring configurations, and national-level subsidy approvals.</p>
          <p><strong>3. Use Restrictions:</strong> Homeowners confirm that accurate customer billing and electricity records are provided for technical verification. User data is utilized strictly for technical feasibility reviews.</p>
          <p><strong>4. Governing Authority:</strong> These terms are governed under Indian jurisdiction and MNRE / regional regulatory framework protocols of West Bengal.</p>
        </div>
      </div>
    </div>
  );
}
